export type ItemClue = {
  name: string
  path: string
}

export const ITEM_CDN_BASE =
  'https://cdn.smitesource.com/cdn-cgi/image/width=512,format=auto,quality=85/'

export const ITEMS: ItemClue[] = [
  { name: "Adamantine Sickle", path: "Items/T2/Icon_T2_AdamantineSickle.png" },
  { name: "Adroit Ring", path: "Items/T2/Icon_T2_AdroitRing.png" },
  { name: "Alchemist Coat", path: "Items/T3/Icon_T3_AlchemistCoat.png" },
  { name: "Amanita Charm", path: "Items/T3/Icon_T3_RestorativeAmanita.png" },
  { name: "Ancient Signet", path: "Items/T3/Icon_T3_AncientSignet.png" },
  { name: "Ancile", path: "Items/T3/Icon_T3_AncileShield.png" },
  { name: "Arondight", path: "Items/T3/Icons_T3_Arondight.png" },
  { name: "Avatar's Parashu", path: "Items/T3/Icon_T3_Parashu.png" },
  { name: "Avenging Blade", path: "Items/T3/Icon_T3_AvengingBlade.png" },
  { name: "Bancroft's Talon", path: "Items/T3/Icon_T3_BancroftsTalon.png" },
  { name: "Barbed Carver", path: "Items/T3/Icon_T3_BarbedCarver.png" },
  { name: "Battle Axe", path: "Items/T2/Icon_T2_BattleAxe.png" },
  { name: "Berserker's Shield", path: "Items/T3/Icons_T3_Berserker.png" },
  { name: "Bifrost Shard", path: "Items/T3/Icons_Curios_BifrostShard.png" },
  { name: "Blood-Bound Book", path: "Items/T3/Icon_T3_Blood-BoundBook.png" },
  { name: "Bloodforge", path: "Items/T3/Icon_T3_BloodForgedBlade.png" },
  { name: "Book of Thoth", path: "Items/T3/Icon_T3_BookofThroth.png" },
  { name: "Bowl Drum", path: "Items/T2/Icon_T2_BowlDrum.png" },
  { name: "Bracer of The Abyss", path: "Items/T3/Icon_T3_HandOfTheAbyss.png" },
  { name: "Bragi's Harp", path: "Items/T3/Icon_T3_BragisHarp.png" },
  { name: "Brawler's Beat Stick", path: "Items/T3/Icon_T3_BrawlersRuin.png" },
  { name: "Breastplate of Valor", path: "Items/T3/Icon_T3_BreastplateOfValor.png" },
  { name: "Caestus", path: "Items/T2/Icon_T2_Caestus.png" },
  { name: "Captain's Ring", path: "Items/T2/Icon_T2_CaptainsRing.png" },
  { name: "Chandra's Grace", path: "Items/T3/Icons_T3_ChandrasGrace.png" },
  { name: "Chronos' Pendant", path: "Items/T3/Icon_T3_ChronosPendant.png" },
  { name: "Circe's Hexstone", path: "Items/T3/Icon_T3_CircesHexstone.png" },
  { name: "Circle of Protection", path: "Items/T2/Icon_T2_Zisurru.png" },
  { name: "Cleric's Cloak", path: "Items/T2/Icon_T2_ClericsCloak.png" },
  { name: "Combat Boots", path: "Items/T2/Icon_T2_CombatBoots.png" },
  { name: "Contagion", path: "Items/T3/Icon_T3_Contagion.png" },
  { name: "Cursed Sickle", path: "Items/T2/Icon_T2_CursedSickle.png" },
  { name: "Dagger of Frenzy", path: "Items/T3/Icon_T3_DaggerOfFrenzy.png" },
  { name: "Damaru", path: "Items/T3/Icon_T3_Damaru.png" },
  { name: "Daybreak Gavel", path: "Items/T3/Icon_T3_DaybreakGavel.png" },
  { name: "Death Metal", path: "Items/T3/Icon_T3_DeathMetal.png" },
  { name: "Deathbringer", path: "Items/T3/Icon_T3_Deathbringer.png" },
  { name: "Demon Blade", path: "Items/T3/Icon_T3_BanefulRapier.png" },
  { name: "Devourer's Gauntlet", path: "Items/T3/Icon_T3_DevoursGloves.png" },
  { name: "Divine Ruin", path: "Items/T3/Icon_T3_DivineRuin.png" },
  { name: "Dominance", path: "Items/T3/Icon_T3_Dominance.png" },
  { name: "Doom Orb", path: "Items/T3/Icon_T3_DoomOrb.png" },
  { name: "Doublet of Binding", path: "Items/T3/Icons_T3_DoubletOfBinding.png" },
  { name: "Draconic Scale", path: "Items/T3/Icons_T3_DraconicScales.png" },
  { name: "Dreamer's Idol", path: "Items/T3/Icon_T3_DreamersIdol.png" },
  { name: "Dwarven Plate", path: "Items/T3/Icon_T3_DwarfForgedPlate_Physical.png" },
  { name: "Enchanted Bracelet", path: "Items/T2/Icon_T2_EnchantedBracelet.png" },
  { name: "Engraved Guard", path: "Items/T2/Icon_T2_EngravedGuard.png" },
  { name: "Eros' Bow", path: "Items/T3/DesignTemp/erosbow.png" },
  { name: "Erosion", path: "Items/T3/Icon_T3_Erosion.png" },
  { name: "Ethereal Staff", path: "Items/T3/Icon_T3_EtherealStaff.png" },
  { name: "Evil Eye", path: "Items/T2/Icon_T2_EvilEye.png" },
  { name: "Eye of Erebus", path: "Items/T3/Icon_T3_EyeOfErebus.png" },
  { name: "Eye of Providence", path: "Items/T3/Icon_T3_EyeOfProvidence.png" },
  { name: "Eye of the Storm", path: "Items/T3/Icon_T3_EyeOfTheStorm.png" },
  { name: "Flaming Pearl", path: "Items/T2/Icon_T2_FlamingPearl.png" },
  { name: "Freya's Tears", path: "Items/T3/Icon_T3_FreyasTears.png" },
  { name: "Gauntlet of Thebes", path: "Items/T3/Icon_T3_GauntletOfThebes.png" },
  { name: "Gem of Focus", path: "Items/T3/Icon_T3_GemOfFocus.png" },
  { name: "Gem of Isolation", path: "Items/T3/Icon_T3_GemOfIsolation.png" },
  { name: "Genji's Guard", path: "Items/T3/Icon_T3_GenjisGuard.png" },
  { name: "Gjallarflare", path: "Items/T3/Icons_Curios_Gjallarflare.png" },
  { name: "Gladiator's Shield", path: "Items/T3/Icon_T3_LorgMor.png" },
  { name: "Glorious Pridwen", path: "Items/T3/Icon_T3_Glorious_Pridwen.png" },
  { name: "Gluttonous Grimoire", path: "Items/T3/Icon_T3_GluttonousGrimoire.png" },
  { name: "Golden Blade", path: "Items/T3/Icon_T3_GoldenBlade.png" },
  { name: "Hastened Fatalis", path: "Items/T3/Icon_T3_HastenedFatalis.png" },
  { name: "Health Chalice", path: "Items/T3/Icons_T3_Container_ChaliceofHealing.png" },
  { name: "Heartseeker", path: "Items/T3/Icon_T3_Heartseeker.png" },
  { name: "Heartwood Charm", path: "Items/T3/Icon_T3_HeartwoodCHarm.png" },
  { name: "Heimdallr's Sight", path: "Items/T3/Icons_Curios_HeimdallrsSight.png" },
  { name: "Helm of Darkness", path: "Items/T3/Icon_T3_HelmOfDarkness.png" },
  { name: "Helm of Radiance", path: "Items/T3/Icon_T3_HelmOfRadiance.png" },
  { name: "Hide of the Nemean Lion", path: "Items/T3/Icon_T3_HideoftheNemeanLion.png" },
  { name: "Hooked Sword", path: "Items/T2/Icon_T2_HookedSword.png" },
  { name: "Hunter's Bow", path: "Items/T2/Icon_T2_HuntersBow.png" },
  { name: "Hussar's Wings", path: "Items/T3/Icon_T3_HussarsWings.png" },
  { name: "Hydra's Lament", path: "Items/T3/Icon_T3_HydrasLament.png" },
  { name: "Infused Axe", path: "Items/T2/Icon_T2_InfusedAxe.png" },
  { name: "Jade Scepter", path: "Items/T3/Icon_T3_JadeScepter.png" },
  { name: "Jotunn's Revenge", path: "Items/T3/Icon_T3_JotunnsRevenge.png" },
  { name: "Killing Stone", path: "Items/T2/Icon_T2_KillingStone.png" },
  { name: "Kinetic Cuirass", path: "Items/T3/Icon_T3_KineticCuirass.png" },
  { name: "Kopesh", path: "Items/T2/Icon_T2_Kopesh.png" },
  { name: "Legionnaire Armor", path: "Items/T2/Icon_T2_LegionnaireArmor.png" },
  { name: "Lernaean Bow", path: "Items/T3/DesignTemp/Icon_T3_LernaeanBow.png" },
  { name: "Leviathan's Hide", path: "Items/T3/Icon_T3_LevianthansHide.png" },
  { name: "Lifebinder", path: "Items/T3/Icon_T3_Lifebinder.png" },
  { name: "Lucerne Hammer", path: "Items/T2/Icon_T2_LucerneHammer.png" },
  { name: "Magi's Cloak", path: "Items/T3/magisshelter.png" },
  { name: "Mana Tome", path: "Items/T2/Icon_T2_ManaTome.png" },
  { name: "Manchu Bow", path: "Items/T2/Icon_T2_ManchuBow.png" },
  { name: "Mantle of Discord", path: "Items/T3/Icon_T3_MantleOfDiscord.png" },
  { name: "Medal of Defense", path: "Items/T2/Icon_T2_MedalOfDefense.png" },
  { name: "Medal of Disruption", path: "Items/T2/Icon_T2_MedalOfDisruption.png" },
  { name: "Mercury's Talaria", path: "Items/T3/Icons_T3_MercurysTalaria.png" },
  { name: "Midgardian Mail", path: "Items/T3/Icons_T3_MidgardianMail.png" },
  { name: "Mote of Chaos", path: "Items/T3/Icon_T3_SoulLocket.png" },
  { name: "Musashi's Dual Swords", path: "Items/T3/Icon_T3_MusashisDualSwords.png" },
  { name: "Mystical Mail", path: "Items/T3/Icons_T3_MysticalMail.png" },
  { name: "Necronomicon", path: "Items/T3/Icon_T3_Necronomicon.png" },
  { name: "Nimble Ring", path: "Items/T3/Icon_T3_NimbleRing.png" },
  { name: "Oath-Sworn Spear", path: "Items/T3/Icon_T3_SerpentSpear.png" },
  { name: "Obsidian Shard", path: "Items/T3/Icon_T3_BalorsEye.png" },
  { name: "Odigba", path: "Items/T2/Icon_T2_IlekeNecklace.png" },
  { name: "Odysseus' Bow", path: "Items/T3/Icon_T3_OdysseusBow.png" },
  { name: "Olmec Blue", path: "Items/T2/Icon_T2_OlmecBlue.png" },
  { name: "Omen Drum", path: "Items/T3/Items_T3_OmenDrum.png" },
  { name: "Oni Hunter's Garb", path: "Items/T3/Icons_T3_OniHuntersGarb.png" },
  { name: "Oracle Staff", path: "Items/T2/Icon_T2_OracleStaff.png" },
  { name: "Pendulum Blade", path: "Items/T3/Icon_T3_PendulumBlade.png" },
  { name: "Pharaoh's Curse", path: "Items/T3/Icon_T3_PharaohsCurse.png" },
  { name: "Phoenix Feather", path: "Items/T3/Icon_T3_PhoenixAmulet.png" },
  { name: "Plated Metal", path: "Items/T2/Icon_T2_PlatedArmor.png" },
  { name: "Polynomicon", path: "Items/T3/Icon_T3_Polynomicon.png" },
  { name: "Prophetic Cloak", path: "Items/T3/Icon_T3_Prophetic_Cloak.png" },
  { name: "Qin's Blade", path: "Items/T3/Icon_T3_QinsBlade.png" },
  { name: "Radiant Bulwark", path: "Items/T3/Icons_T3_RadiantBulwark.png" },
  { name: "Rage", path: "Items/T3/Icon_T3_Rage.png" },
  { name: "Ragnarok's Wake", path: "Items/T3/Icons_RagnaroksWake.png" },
  { name: "Regrowth Striders", path: "Items/T3/Icon_T3_RegrowthStriders.png" },
  { name: "Resolute Mantle", path: "Items/T3/Icons_T3_ResoluteMantle.png" },
  { name: "Ring of Dispel", path: "Items/T2/Icon_T2_RingOfDispel.png" },
  { name: "Riptalon", path: "Items/T3/Icons_T3_Riptalon.png" },
  { name: "Rod of Asclepius", path: "Items/T3/DesignTemp/RodofAscelpius_T3.png" },
  { name: "Rod of Tahuti", path: "Items/T3/Icon_T3_EldritchOrb.png" },
  { name: "Runeforged Hammer", path: "Items/T3/Icon_T3_RuneforgedHammer.png" },
  { name: "Runic Hide", path: "Items/T2/Icon_T2_RunicHide.png" },
  { name: "Sage's Ring", path: "Items/T2/Icon_T2_SagesRing.png" },
  { name: "Sanguine Lash", path: "Items/T3/Icon_T3_SanguineLash.png" },
  { name: "Scepter of Dominion", path: "Items/T3/Icon_T3_ScepterofDominion.png" },
  { name: "Screeching Gargoyle", path: "Items/T3/Icon_T3_ScreechingGargoyle.png" },
  { name: "Shield of the Phoenix", path: "Items/T3/Icon_T3_ShieldOfThePhoenix.png" },
  { name: "Shield Splitter", path: "Items/T3/DesignTemp/shieldsplitter.png" },
  { name: "Shifter's Shield", path: "Items/T3/Icon_T3_ShapeShifterShield.png" },
  { name: "Shogun's Ofuda", path: "Items/T3/Icon_T3_ShogunsOfuda.png" },
  { name: "Shroud Of Vengeance", path: "Items/T3/Icons_T3_ShroudOfVengeance.png" },
  { name: "Silverbranch Bow", path: "Items/T3/Icon_T3_SilverbranchBow.png" },
  { name: "Skeggox", path: "Items/T2/Icon_T2_Skeggox.png" },
  { name: "Soul Gem", path: "Items/T3/Icons_T3_SoulGem.png" },
  { name: "Soul Reaver", path: "Items/T3/Icon_T3_SoulDevourer.png" },
  { name: "Soul Reliquary", path: "Items/T2/Icon_T2_SoulReliquary.png" },
  { name: "Spear of Desolation", path: "Items/T3/Icon_T3_SpearofDesolation.png" },
  { name: "Spear Of The Magus", path: "Items/T3/Icons_T3_SpearoftheMagus.png" },
  { name: "Spectral Armor", path: "Items/T3/Icon_T3_SpectralArmor.png" },
  { name: "Sphere of Negation", path: "Items/T3/Icon_T3_SphereOfNegation.png" },
  { name: "Spirit Robe", path: "Items/T3/Icon_T3_SpiritRobe.png" },
  { name: "Staff of Myrddin", path: "Items/T3/Icon_T3_StaffOfMyrddin.png" },
  { name: "Stalwart Sigil", path: "Items/T2/Icon_T2_Sigil.png" },
  { name: "Stampede", path: "Items/T3/Icon_T3_Stampede.png" },
  { name: "Stone of Binding", path: "Items/T3/Icon_T3_BindingsOfLyngvi.png" },
  { name: "Stygian Anchor", path: "Items/T3/Icons_T3_StygianAnchor.png" },
  { name: "Sun Beam Bow", path: "Items/T3/Icons_DesignTemp_T3_NewSunBeamBow.png" },
  { name: "Survivor's Sash", path: "Items/T2/Icon_T2_SurvivorsSash.png" },
  { name: "Talisman of Purification", path: "Items/T3/Icon_T3_TalismanOfPurification.png" },
  { name: "Tekko-Kagi", path: "Items/T3/Icon_T3_TekkoKagi.png" },
  { name: "The Cosmic Horror", path: "Items/T3/Icon_T3_StaffOfCosmicHorror.png" },
  { name: "The Crusher", path: "Items/T3/Icon_T3_Crusher.png" },
  { name: "The Executioner", path: "Items/T3/Icon_T3_TheExecutioner.png" },
  { name: "The Reaper", path: "Items/T3/Icon_T3_TheReaper.png" },
  { name: "The World Stone", path: "Items/T3/Icon_T3_TheWorldStone.png" },
  { name: "Titan's Bane", path: "Items/T3/Icon_T3_ObsidianMacuahuitl.png" },
  { name: "Totem of Death", path: "Items/T3/Icon_T3_TotemOfDeath.png" },
  { name: "Toxic Blade", path: "Items/T3/Icons_T3_ToxicBlade.png" },
  { name: "Transcendence", path: "Items/T3/Icon_T3_Transcendence.png" },
  { name: "Triton's Conch", path: "Items/T3/Icon_T3_TritonsConch.png" },
  { name: "Typhon's Heart", path: "Items/T3/Icon_T3_TyphonsHeart.png" },
  { name: "Tyrfing", path: "Items/T3/Icon_T3_Tyrfing.png" },
  { name: "Umbral Link", path: "Items/T3/Icon_T3_UmbralLink.png" },
  { name: "Veve Charm", path: "Items/T2/Icon_T2_VeveCharm.png" },
  { name: "Vital Amplifier", path: "Items/T3/Icon_T3_VitalAmplifier.png" },
  { name: "Void Shard", path: "Items/T2/Icon_T2_VoidShard.png" },
  { name: "Void Shield", path: "Items/T3/Icon_T3_VoidShield.png" },
  { name: "Void Stone", path: "Items/T3/Icon_T3_VoidStone.png" },
  { name: "Warding Chalice", path: "Items/T3/Icons_T3_Container_ChaliceoftheOracle.png" },
  { name: "Wish-Granting Pearl", path: "Items/T3/Icon_T3_Wish-GrantingPearl.png" },
  { name: "Wyrmskin Hide", path: "Items/T3/Icons_T3_WyrmskinHide.png" },
  { name: "Xibalban Effigy", path: "Items/T3/Icons_T3_XibalbanEffigyNew.png" },
  { name: "Yogi's Necklace", path: "Items/T3/Icon_T3_YogisNecklace.png" },
  { name: "Zither", path: "Items/T2/Icon_T2_Zither.png" },
]
